//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.results = new HashSet<result>();
        }

        [Required]
        [RegularExpression(@"^[0-9]{8}$", ErrorMessage = "Student ID is 8 digits.")]
        [Remote("IsStudentIDUsed", "students", HttpMethod = "POST", ErrorMessage = "Student ID already exists in database.")]
        public string studentID { get; set; }
        [Required]
        [RegularExpression(@"[a-zA-Z ]{1,30}", ErrorMessage = "Type in up to 30 upper or lowercase letters or spaces")]
        public string studentName { get; set; }
        public string studentPhoto { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<result> results { get; set; }
    }
}
